name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: yarn install
      working-directory: ./account-management-api

    - name: Build
      run: yarn build
      working-directory: ./account-management-api

    - name: Run Unit Tests
      run: yarn test
      working-directory: ./account-management-api

    - name: Run E2E Tests
      run: yarn test:e2e
      working-directory: ./account-management-api
